# <!-- Powered by BMAD™ Core -->
markdownExploder: true
qa:
  qaLocation: docs/bmad/qa
prd:
  prdFile: docs/bmad/brownfield-prd.md
  prdVersion: v4
  prdSharded: true
  prdShardedLocation: docs/bmad/brownfield-prd
  epicFilePattern: epic-{n}*.md
architecture:
  architectureFile: docs/bmad/brownfield-architecture.md
  architectureVersion: v4
  architectureSharded: true
  architectureShardedLocation: docs/bmad/brownfield-architecture
customTechnicalDocuments: null
devLoadAlwaysFiles:
  - docs/bmad/brownfield-architecture/index.md
  - docs/bmad/brownfield-architecture/confluence-integration-architecture.md
devDebugLog: .ai/debug-log.md
devStoryLocation: docs/bmad/stories
slashPrefix: BMad
